# Generated by Django 5.2.14 on 2026-05-14 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["group_name"],
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="academic_degree",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Учёная степень"
            ),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="is_verified",
            field=models.BooleanField(default=True, verbose_name="Проверен"),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="work_experience",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Стаж работы (лет)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватар"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата регистрации"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "teacher"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("teacher", "Teacher"),
                    ("student", "Student"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BulkImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="imports/%Y/%m/%d/", verbose_name="Файл импорта"
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("students", "Студенты"),
                            ("teachers", "Преподаватели"),
                            ("groups", "Группы"),
                        ],
                        max_length=20,
                        verbose_name="Тип импорта",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершён"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(default=0, verbose_name="Всего строк"),
                ),
                (
                    "successful_rows",
                    models.PositiveIntegerField(default=0, verbose_name="Успешных"),
                ),
                (
                    "failed_rows",
                    models.PositiveIntegerField(default=0, verbose_name="Ошибок"),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, verbose_name="Журнал ошибок"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Импорт данных",
                "verbose_name_plural": "Импорт данных",
                "db_table": "bulk_imports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Номер зачётной книжки"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Контакт для экстренных случаев",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль студента",
                "verbose_name_plural": "Профили студентов",
                "db_table": "student_profiles",
            },
        ),
    ]
