# Generated by Django 5.2.14 on 2026-05-14 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_group_options_alter_user_options_and_more"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-year", "-semester", "subject__code"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["course", "day_of_week", "start_time"],
                "verbose_name": "Занятие",
                "verbose_name_plural": "Расписание",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["code"],
                "verbose_name": "Дисциплина",
                "verbose_name_plural": "Дисциплины",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание курса"),
        ),
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="week_end",
            field=models.DateField(blank=True, null=True, verbose_name="Конец недели"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="week_start",
            field=models.DateField(blank=True, null=True, verbose_name="Начало недели"),
        ),
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Семестр изучения"
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="year",
            field=models.PositiveIntegerField(
                default=2025, verbose_name="Учебный год"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="accounts.group",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="courses.subject",
            ),
        ),
        migrations.CreateModel(
            name="CourseAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_submissions", models.PositiveIntegerField(default=0)),
                ("graded_submissions", models.PositiveIntegerField(default=0)),
                ("late_submissions", models.PositiveIntegerField(default=0)),
                (
                    "average_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "fail_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аналитика курса",
                "verbose_name_plural": "Аналитика курсов",
                "db_table": "course_analytics",
            },
        ),
        migrations.CreateModel(
            name="DeadlineTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_deadline_offset",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Отступ дедлайна (минуты)"
                    ),
                ),
                (
                    "allow_weekend_submission",
                    models.BooleanField(
                        default=False, verbose_name="Принимать работы в выходные"
                    ),
                ),
                (
                    "late_penalty_percent",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Штраф за опоздание (%)"
                    ),
                ),
                (
                    "max_late_days",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Макс. дней для поздней сдачи"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadline_template",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон дедлайнов",
                "verbose_name_plural": "Шаблоны дедлайнов",
                "db_table": "deadline_templates",
            },
        ),
    ]
