# Generated by Django 5.2.14 on 2026-05-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_options_alter_schedule_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="semester",
            field=models.PositiveIntegerField(verbose_name="Семестр изучения"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Учебный год"),
        ),
    ]
