# Generated by Django 5.2.14 on 2026-05-14 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_subject_semester_alter_subject_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_number",
                    models.PositiveIntegerField(verbose_name="Номер слота"),
                ),
                ("deadline", models.DateTimeField(verbose_name="Дедлайн")),
                (
                    "is_filled",
                    models.BooleanField(default=False, verbose_name="Заполнен"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот задания",
                "verbose_name_plural": "Слоты заданий",
                "db_table": "course_slots",
                "ordering": ["course", "deadline"],
            },
        ),
    ]
