# Generated by Django 5.2.14 on 2026-05-14 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="submissions/%Y/%m/%d/", verbose_name="Файл работы"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает проверки"),
                            ("graded", "Проверено"),
                            ("revision", "На доработке"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "is_late",
                    models.BooleanField(default=False, verbose_name="Позже дедлайна"),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Баллы"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Максимум баллов"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, verbose_name="Комментарий преподавателя"
                    ),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа студента",
                "verbose_name_plural": "Работы студентов",
                "db_table": "submissions",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False, verbose_name="Внутренний комментарий"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="assignments.submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "db_table": "feedbacks",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название задания"),
                ),
                ("description", models.TextField(verbose_name="Описание задания")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("homework", "Домашняя работа"),
                            ("project", "Проект"),
                            ("lab", "Лабораторная"),
                            ("test", "Тест"),
                        ],
                        default="homework",
                        max_length=20,
                    ),
                ),
                (
                    "max_points",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Максимальные баллы"
                    ),
                ),
                ("deadline", models.DateTimeField(verbose_name="Дедлайн")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
                "db_table": "tasks",
            },
        ),
        migrations.AddField(
            model_name="submission",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="assignments.task",
            ),
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant_number",
                    models.PositiveIntegerField(verbose_name="Номер варианта"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assignments.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение задания",
                "verbose_name_plural": "Назначения заданий",
                "db_table": "task_assignments",
                "unique_together": {("task", "student")},
            },
        ),
        migrations.AddField(
            model_name="submission",
            name="task_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="assignments.taskassignment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("task", "student")},
        ),
    ]
