# Generated by Django 5.2.14 on 2026-05-14 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
        ("courses", "0002_alter_course_options_alter_schedule_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Работа студента",
                "verbose_name_plural": "Работы студентов",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-deadline"],
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
            },
        ),
        migrations.AddField(
            model_name="feedback",
            name="is_resolved",
            field=models.BooleanField(default=False, verbose_name="Решено"),
        ),
        migrations.AddField(
            model_name="submission",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="Версия"),
        ),
        migrations.AddField(
            model_name="task",
            name="allow_late_submission",
            field=models.BooleanField(
                default=False, verbose_name="Разрешить позднюю сдачу"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="task_attachments/",
                verbose_name="Материалы",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="instructions_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на инструкцию"),
        ),
        migrations.AddField(
            model_name="task",
            name="late_penalty_percent",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Штраф за опоздание (%)"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="assigned_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает проверки"),
                    ("graded", "Проверено"),
                    ("revision", "На доработке"),
                    ("rejected", "Отклонена"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("homework", "Домашняя работа"),
                    ("project", "Проект"),
                    ("lab", "Лабораторная"),
                    ("test", "Тест"),
                    ("exam", "Экзамен"),
                    ("quiz", "Квик-тест"),
                ],
                default="homework",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SubmissionAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_assigned", models.PositiveIntegerField(default=0)),
                ("total_submitted", models.PositiveIntegerField(default=0)),
                ("total_graded", models.PositiveIntegerField(default=0)),
                (
                    "average_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "median_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "min_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "late_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_analytics",
                        to="courses.course",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="assignments.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аналитика сдачи",
                "verbose_name_plural": "Аналитика сдачи",
                "db_table": "submission_analytics",
            },
        ),
        migrations.CreateModel(
            name="TaskBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название пакета"),
                ),
                ("tasks_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_batches",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет задач",
                "verbose_name_plural": "Пакеты задач",
                "db_table": "task_batches",
            },
        ),
    ]
