# Generated by Django 5.2.14 on 2026-05-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assignments",
            "0002_alter_feedback_options_alter_submission_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
    ]
